# Generated by Django 2.2.10 on 2020-10-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('img', models.TextField(blank=True, max_length=500)),
                ('add_img', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
